spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order-hub}
    username: ${SPRING_DATASOURCE_USERNAME:e-mall}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE

management:
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development

server:
  port: ${SPRING_PORT:8084}